[build-system]
requires = ["meson-python>=0.15.0", "numpy>=2.0"]
build-backend = "mesonpy"

[project]
name = "guptri_py"
version = "0.1.0"
description = "Singular generalized eigenvalue problems. "
readme = "README.rst"
requires-python = ">=3.10"
license = "MIT"
license-files = ["LICENSE.txt"]
authors = [
    { name = "Markus Wageringel" }
]
keywords = ["guptri", "generalized eigenvalues", "matrix pencils", "singular pencils", "fortran"]
dependencies = ["numpy"]

[project.urls]
Documentation = "https://guptri-py.readthedocs.io"
Repository = "https://github.com/mwageringel/guptri_py.git"

[dependency-groups]
dev = [
    "pytest>=8.4.2",
]
